#!/usr/bin/env bash
set -euo pipefail

SECRET_NAME="drella-secrets"
AWS_REGION="us-east-1"
HOME_DIR="/var/home/drella"

SECRET_JSON=$(aws secretsmanager get-secret-value \
    --region "${AWS_REGION}" \
    --secret-id "${SECRET_NAME}" \
    --query SecretString \
    --output text)

# GCloud application default credentials
GCLOUD_DIR="${HOME_DIR}/.config/gcloud"
GCLOUD_FILE="${GCLOUD_DIR}/application_default_credentials.json"
install -d -o drella -g drella -m 0700 "${GCLOUD_DIR}"
echo "${SECRET_JSON}" | jq -r '.gcloud_credentials' > "${GCLOUD_FILE}"
chown drella:drella "${GCLOUD_FILE}"
chmod 0600 "${GCLOUD_FILE}"

# GitHub CLI auth token
echo "${SECRET_JSON}" | jq -r '.gh_token' | sudo --set-home --user=drella gh auth login --with-token --git-protocol https
